### ISSUE TITLE
No perfect hits with RGI: program crashes

### ISSUE THREAD

**Issue by MatteoSchiavinato** [meglab-metagenomics/amrplusplus_v2#10]
Hi,

My amr++ run crashed when it reached the runRGI step. The reason seems to be that no "perfect hits" file is created, probably because there are none, only many "strict hits". 

Reading into the nextflow file (`*_withRGI_Kraken.nf`) I see that lines 562-563 are:
```
     output:
         set sample_id, file("${sample_id}_rgi_perfect_hits.csv") into perfect_snp_long_hits
```
And that output is used as input shortly after, at line 576:
```
         set sample_id, file(perfect_rgi_counts) from perfect_snp_long_hits
```
I suppose the script that takes care of those hits (`RGI_aro_hits.py`) should at least "touch" those files, but it seems as if it doesn't.

What happens when no "perfect hits" file is created, if there are none?

**Comment by EnriqueDoster** [comment]
Hi @MatteoSchiavinato, super late but we'll be responding to your old questions anyway!

Early on we decided that AMR++ would only consider the results from the "strict" algorithm, but I see how reporting all of the results could be useful too. Right now those results would be created and stored in the temporary work directory, but they are not included in the results directory. 

You will likely see this in other responses to your questions or on the READ.ME file, but we will be updating AMR++ sometime soon and we'll include an alternative for SNP confirmation. Thanks!
