### ISSUE TITLE
Feature request: early-stage check for read names containing '#'

### ISSUE THREAD

**Issue by MatteoSchiavinato** [meglab-metagenomics/amrplusplus_v2#11]
Dear meglab team, 

I have been working with AMR++ in the last month, and I noticed that reads having "#" in their read name make the pipeline crash at the RGI stage. 

This problem is surely an RGI-dependent issue, not yours, but it would be very helpful if the pipeline performed a read name check in the early stages of the pipeline, ideally in the first step before the QC. This way, the user won't have to wait hours for it to crash.

Also, RGI does not provide any feedback on that error, it simply ignores the read, so it took me ages to figure out.

**Comment by EnriqueDoster** [comment]
@MatteoSchiavinato, I had no idea that this caused an issue with RGI!
As you've seen in the other comments, we're discontinuing our support for RGI. We'll definitely keep this in mind in case we decide to incorporate RGI again. 

Thanks!
