### ISSUE TITLE
container creation failed error using Microbial_Ecology_Group_AMR_AMI

### ISSUE THREAD

**Issue by milobrooks** [meglab-metagenomics/amrplusplus_v2#2]
Hello
I created an instance of the AMI named "Microbial_Ecology_Group_AMR_AMI but when I run the command

 nextflow run main_AmrPlusPlus_v2.nf -profile singularity --output test

The workflow terminates with the following error message

Command error:
  FATAL:   container creation failed: mount /proc/self/fd/6->/var/singularity/mnt/session/rootfs error: can't mount image /proc/self/fd/6: failed to find loop device: could not attach image file to loop device: Failed to set loop flags on loop device: resource temporarily unavailable

Work dir:
  /home/ec2-user/amrplusplus_v2/work/f8/b1d762119203a4a6773951b198593a

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`

Are there some privileges that need changing?

**Comment by EnriqueDoster** [comment]
Hello Milo,

Thanks for submitting your question here. I saw your other email about having difficulty finding the AMI, can I now assume you got it working?

If you testing the AMR++ script within the AMI, just change the flag "-profile" to work with the AMI environment like this:
> nextflow run main_AmrPlusPlus_v2.nf -profile MEG_AMI --output test

We installed all of the necessary tools in the AMI locally, so we don't have to use the singularity container. Try that out and let me know what if that works!

Best,
Enrique

**Comment by milobrooks** [comment]
Hi Enrique

I managed to get the AMI running for most of the script using the local profile but it ran out of RAM during execution.  I believe this is because I am using the somewhat underpowered t2_micro instance on Amazon Web Services which only has 16G storage and 1GB RAM.  When I installed amrplusplus_v2 on our own server using the latest commit it worked fine.
  
Thanks
Milo
