### ISSUE TITLE
kraken2 database error

### ISSUE THREAD

**Issue by nysdan** [meglab-metagenomics/amrplusplus_v2#6]
Hello! 
I've been trying to run main_AmrPlusPlus_v2_withKraken.nf, but i always get stuck when running kraken2 using minikraken2 database locally installed:
Error: (.nextflow.log)

```
kraken2 --db /path/to/kraken2/db/minikraken_8GB_20200312 --confidence 1 --paired sample_id.non.host.R1.fastq.gz sample_id.non.host.R2.fastq.gz --threads 3 --report sample_id.
kraken.filtered.report > sample.kraken.filtered.raw
kraken2: database ("/path/to/kraken2/db/minikraken_8GB_20200312") does not contain necessary file taxo.k2d
```
The kraken2 database folder contains all required files (including taxo.k2.d):

```
ls ../../DB/kraken2/minikraken_8GB_20200312/
README.md                     database150mers.kmer_distrib  database250mers.kmer_distrib  hash.k2d  seqid2taxid.map
database100mers.kmer_distrib  database200mers.kmer_distrib  database50mers.kmer_distrib   opts.k2d  taxo.k2d
```

I've run kraken2 using the same database with no errors, using a kraken2 locally installed.
I'll appreciate any hints to overcome this

Thaks

**Comment by srjun** [comment]
I ran into the same problem. I have standard kraken2 database which contains taxo.k2d. Could you let me know how you resolved the error if you did? Thanks.

**Comment by EnriqueDoster** [comment]
Hello nysdan and srjun, we apologize for not responding earlier and we hope everything worked out okay. Please see the update on the [READ.ME file](https://github.com/meglab-metagenomics/amrplusplus_v2/blob/master/README.md) where we announce an upcoming update.

In case you didn't figure out your issue with Kraken and it's still relevant, I think I have see what is causing the issue. It looks like the "kraken_db" variable was not updated so AMR++ defaulted to using this "/path/to/kraken2/db/minikraken_8GB_20200312". However, this seems to be different than your example for the kraken database that you have locally, "../../DB/kraken2/minikraken_8GB_20200312/".

I think you just have to add the "--kraken_db " variable to the main command and make sure that you use the absolute path for your local kraken2 database. I believe this was the issue so I will be closing this comment, but please let us know if you are still running into issues. Thank you!
