### ISSUE TITLE
Program version for single-end reads

### ISSUE THREAD

**Issue by MatteoSchiavinato** [meglab-metagenomics/amrplusplus_v2#8]
Dear Authors, 

I have tried to use your program but I quickly realized that the scripts are hardcoded with commands optimized for paired-end reads. As far as I could find, there are no versions for single-end reads.

Will this be done in the future? 

Thanks, 
Matteo

**Comment by MatteoSchiavinato** [comment]
I have made two nextflow scripts myself modifying yours, so that they would work with single end reads. I would like to make a pull request for these, so that you can integrate them in the main repository. I think some other people would appreciate having a tool version that works with single end reads!

**Comment by NataliHB** [comment]
Hi Mateo,

Could you share those two scripts? I am trying to run the pipeline with single end reads and as you mentioned the original is optimized for paired-end reads. 

Thanks! 

Natali

**Comment by MatteoSchiavinato** [comment]
Sure, send me an email at the address you find here!
https://boku.ac.at/personen/person/F5BB443F550FA189

**Comment by EnriqueDoster** [comment]
Hi @MatteoSchiavinato, thanks for the suggestion. We will definitely add this feature to the next update. If you'd be willing, could you please share your scripts with me at this email: enriquedoster@gmail.com. I'd also be happy to hear any other ideas you might have for further improvements. Thanks!

**Comment by MatteoSchiavinato** [comment]
Hi Enrique, to be honest I think my modifications are not of great value. I wasn't an expert of Nextflow back then (I am now) and when looking at that code, it embarrasses me a little.
