### ISSUE TITLE
Host index uncertainty

### ISSUE THREAD

**Issue by MatteoSchiavinato** [meglab-metagenomics/amrplusplus_v2#9]
Hi, 

I am running the `main_AmrPlusPlus_v2_withRGI_Kraken.nf` workflow, and I'm doing it with `--host_index`. 

I'm not sure I'm doing things correctly, since the [usage page](https://github.com/meglab-metagenomics/amrplusplus_v2/blob/master/docs/usage.md) says `--index` and not `--host_index`. 

I just wanted to bring this up, because the `--help` says `--host_index`, from the script. 

I would suggest a slight modification of the option, that could be easier to understand. Instead of having to declare all the index file using the `*` wildcard, it would be easier if people had to declare the index prefix including the path (like in bowtie2 for example). 

That way, the `--host` option would be automatically checked for the existence of an index by checking if it has the index files with the same prefix, and the user would only have to index the FASTA reference file using `bwa index ${REF}`.

**Comment by EnriqueDoster** [comment]
Hi @MatteoSchiavinato, thanks for the feedback! I see what you mean and I'll try it out on our next update. For now, we updated the usage page.
